# Generated by Django 3.0.3 on 2020-02-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='seat_nos',
            field=models.IntegerField(),
        ),
    ]
