# Generated by Django 3.0.3 on 2020-02-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_auto_20200215_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.CharField(default='start to destination of trip', max_length=100),
        ),
    ]
