# Generated by Django 3.0.3 on 2020-02-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0003_route_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='approximate_time',
            field=models.DurationField(default='08:00:00'),
        ),
    ]
