# Generated by Django 3.0.3 on 2020-02-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0004_auto_20200215_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='layout',
            field=models.CharField(max_length=5),
        ),
    ]
